### ISSUE TITLE
Share your work with Mattermost community?

### ISSUE THREAD

**Issue by jasonblais** [moussetc/mattermost-plugin-dice-roller#1]
Hi @moussetc ,

We just created a repository to list plugins built by the Mattermost community: https://github.com/mattermost/mattermost-plugins

Similar to my post at https://github.com/moussetc/mattermost-plugin-giphy/issues/7, we'd love to help share your plugin with the Mattermost community, in addition to our [App Directory](https://about.mattermost.com/community-applications/).

If you're interested to have it included as an unofficial plugin, you just need to run one command, similar to

```
git submodule add https://github.com/mattermost/mattermost-plugin-profanity-filter.git Unofficial/mattermost-plugin-profanity-filter
```

Let me know if you have any questions!

**Comment by Hanzei** [comment]
This repository has been added to https://github.com/mattermost/mattermost-plugins. I think this issue can be closed.

**Comment by jasonblais** [comment]
Good catch! Closing
