### ISSUE TITLE
Plugin Unavailable

### ISSUE THREAD

**Issue by VenturaFranklin** [moussetc/mattermost-plugin-dice-roller#13]
On Mattermost Version: 5.26.1
The Dice Roller plugin does not exist in the plugin marketplace.

> In Mattermost 5.16 and later:
> 
> In Mattermost, go to Main Menu > Plugin Marketplace.
> Search for the "Dice Roller" plugin, then click Install to install it.
> Activate the plugin in the System Console > Plugins Management > Management page

**Comment by moussetc** [comment]
Thanks for pointing this to me! As the Marketplace submission is waiting in review limbo (the state of the submission can be followed [here](https://github.com/mattermost/mattermost-marketplace/issues/122)), I've updated the doc temporarily to remove mention of the marketplace.

**Comment by moussetc** [comment]
As of today, the 3.1.1 version of the Dice Roller Mattermost plugin is available on the official Mattermost marketplace :tada: The doc has been updated accordingly.
