### ISSUE TITLE
/roll help not working

### ISSUE THREAD

**Issue by AnestisK** [moussetc/mattermost-plugin-dice-roller#14]
Hi,

I installed the latest release on my MatterMost server.
However, the /roll help command doesn't seem to work.
If I type in an actual roll command (i.e. /roll 2d6), that works.

**Comment by moussetc** [comment]
Hi and thanks for reporting the issue. Could you give the versions of your mattermost server, diceroller plugin and client (desktop app, android app...) ?

**Comment by AnestisK** [comment]
Nevermind.  Was a misconfiguration on the side of Apache.  It's working now after enabling proxy_ajp for Apache (which fixed wss:// errors as well).
