### ISSUE TITLE
Installing Plugin with MM 6.0.2 is not possible

### ISSUE THREAD

**Issue by dragonpil** [moussetc/mattermost-plugin-dice-roller#17]
When I try to install this plugin with MM 6.0.2 server I get: 
Unable to move plugin from temporary directory to final destination. Another plugin may be using the same directory name.

**Comment by moussetc** [comment]
Hi, thanks for the report.

Can you please run the following command first and then observe if you are still facing the same issue when you are attempting to load the plugins?
 
`sudo chown -R mattermost:mattermost /opt/mattermost` (adapt the Mattermost directory path to your own installation)

Run the tail -f /opt/mattermost/log/mattermost.log command to observe while you attempt to reproduce the issue again after you run the command above.

(steps from the [Mattermost forum](https://forum.mattermost.org/t/plugins-not-loading/11493/4))

**Comment by dragonpil** [comment]
Thanks Issue solved... 
Problem was that mattermost/plugins contained old dice-roller plugin (from before upgrade)
