### ISSUE TITLE
Large number of rolls stops plugin from responding correctly.

### ISSUE THREAD

**Issue by RobbieDubya** [moussetc/mattermost-plugin-dice-roller#3]
As soon as our admin installed the plugin, i tried:

`/roll 123412341234d1234`

**Comment by Taffer** [comment]
As Rob's admin, can confirm. Not sure if it's still working on producing an insane number of rolls or what.

It's going to flood the channel, isn't it? 😨

**Comment by Taffer** [comment]
Disabling/enabling the plugin at least made it responsive again.

**Comment by Taffer** [comment]
Fixed in pull request #5

**Comment by moussetc** [comment]
Thanks to @RobbieDubya for being a good tester and to @Taffer for contributing! 
The new v2.0.1 release that contain both patches for #3 and #4 is available for download.
