### ISSUE TITLE
missing image

### ISSUE THREAD

**Issue by tgly307** [moussetc/mattermost-plugin-dice-roller#8]
![image](https://user-images.githubusercontent.com/25153311/56903469-f0f66e80-6ace-11e9-817e-b2b7b77e89a1.png)

The url of this image is `https://mysite.com/api/v4/image?url=%2Fplugins%2Fcom.github.moussetc.mattermost.plugin.diceroller%2Ficon.png`
I got a 403 forbidden error when request this image.

**Comment by moussetc** [comment]
Please give some details about your installation:
- plugin version
- Mattermost version
- OS
- Do you have anything that appears in your Mattermost logs (cf. System Console) when the request fails?
- Have you set the Site URL configuration value?
- Is the Mattermost image proxy enabled?

**Comment by tgly307** [comment]
thanks a lot! I found my image proxy enabled, plugin works when I turn it down. I will close this issue.
